packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

overrides:
  "minimatch@>=9.0.0 <9.0.7": ">=9.0.7"
  "flatted@<3.4.2": ">=3.4.2"
  "brace-expansion@>=2.0.0 <2.0.3": ">=2.0.3"
  "brace-expansion@>=4.0.0 <5.0.5": ">=5.0.5"

allowBuilds:
  "@firebase/util": true
  core-js: true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  workerd: true
